import React,{useRef,useState} from "react";
import {ChevronDown,KeyRound,LogOut,Settings,Upload,X} from "lucide-react";
import {supabase} from "./supabaseClient";

const readImage=file=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file);});
export default function ProfileSystemModal({user,account,onClose,onSaveAccount,onLogout,onMessage}){
  const [name,setName]=useState(user.user_metadata?.display_name||account.name||"Trader"),[photo,setPhoto]=useState(user.user_metadata?.profile_image||account.profileImage||""),[theme,setTheme]=useState(account.theme||"dark"),[timeout,setTimeoutValue]=useState(Number(user.user_metadata?.session_timeout)||0),[open,setOpen]=useState({profile:true,appearance:true,security:true}),[busy,setBusy]=useState(false),[password,setPassword]=useState("");
  const fileRef=useRef(null),section=(id,title,note,children)=><section className="ref-profile-section"><button type="button" onClick={()=>setOpen(v=>({...v,[id]:!v[id]}))}><span><b>{title}</b><small>{note}</small></span><ChevronDown size={15} style={{transform:open[id]?"rotate(180deg)":"none"}}/></button>{open[id]&&<div>{children}</div>}</section>;
  const save=async()=>{setBusy(true);const metadata={...user.user_metadata,display_name:name.trim()||"Trader",profile_image:photo,session_timeout:timeout};const {error}=await supabase.auth.updateUser({data:metadata});if(error){onMessage(error.message);setBusy(false);return;}const ok=await onSaveAccount({...account,name:account.name,profileImage:photo,theme});setBusy(false);if(ok!==false)onClose();};
  const changePassword=async()=>{if(password.length<6)return onMessage("Password must be at least 6 characters.");setBusy(true);const {error}=await supabase.auth.updateUser({password});setBusy(false);onMessage(error?error.message:"Password updated.");if(!error)setPassword("");};
  return <div className="tj-modal-overlay" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="tj-modal tj-modal-wide ref-profile-modal"><header className="tj-modal-head"><b><Settings size={15}/> Profile &amp; System</b><button className="tj-icon-btn" onClick={onClose}><X size={17}/></button></header><div className="tj-modal-body">
    <div className="ref-profile-hero"><div className="ref-profile-avatar">{photo?<img src={photo} alt="Profile"/>:<span>{name.slice(0,1).toUpperCase()}</span>}</div><div><small>Profile Preferences</small><h2>{name}</h2><p>{user.email}</p></div><div><small>Active Account</small><b>{account.name}</b><p>{theme} surface</p></div></div>
    {section("profile","Profile Preferences","Name, signed-in email, and profile photo",<><div className="ref-profile-photo"><div className="ref-profile-avatar">{photo?<img src={photo} alt="Profile preview"/>:<span>{name.slice(0,1).toUpperCase()}</span>}</div><div><b>{name}</b><small>{photo?"Custom profile image active":"Account badge fallback active"}</small><span><button className="tj-btn-outline tj-btn-small" onClick={()=>fileRef.current?.click()}><Upload size={13}/> Upload photo</button>{photo&&<button className="tj-btn-outline tj-btn-small" onClick={()=>setPhoto("")}>Remove photo</button>}</span><input ref={fileRef} hidden type="file" accept="image/*" onChange={async e=>{const f=e.target.files?.[0];if(f)setPhoto(await readImage(f));e.target.value="";}}/></div></div><label className="tj-field"><span className="tj-field-label">Display Name</span><input className="tj-input" value={name} onChange={e=>setName(e.target.value)}/></label><label className="tj-field"><span className="tj-field-label">Signed-in Email</span><input className="tj-input" value={user.email||""} disabled/></label></>)}
    {section("appearance","Appearance","Choose the surface used throughout your workspace",<div className="ref-theme-cards"><button className={theme==="dark"?"is-active":""} onClick={()=>setTheme("dark")}><i className="ref-theme-dark"/><b>Dark</b><small>Deep focus with quiet contrast</small></button><button className={theme==="light"?"is-active":""} onClick={()=>setTheme("light")}><i className="ref-theme-light"/><b>Light</b><small>Bright workspace with clear surfaces</small></button></div>)}
    {section("security","Session & Security","Control inactivity sign-out and account access",<><label className="tj-field"><span className="tj-field-label">Auto sign-out</span><select className="tj-input" value={timeout} onChange={e=>setTimeoutValue(Number(e.target.value))}><option value="0">Never on inactivity</option><option value="15">After 15 minutes</option><option value="30">After 30 minutes</option><option value="60">After 1 hour</option><option value="120">After 2 hours</option></select><small className="tj-muted-txt">This applies to this signed-in profile across every trading account in the journal.</small></label><div className="ref-password-row"><input type="password" className="tj-input" placeholder="New password (6+ characters)" value={password} onChange={e=>setPassword(e.target.value)}/><button className="tj-btn-outline" onClick={changePassword} disabled={busy}><KeyRound size={14}/> Change password</button></div><button className="tj-btn-outline ref-logout" onClick={onLogout}><LogOut size={14}/> Log out of this device</button></>)}
    <div className="tj-modal-actions"><button className="tj-btn-outline" onClick={onClose}>Cancel</button><button className="tj-btn-primary" onClick={save} disabled={busy}>{busy?"Saving…":"Save Profile"}</button></div>
  </div></div></div>;
}
