import React, {useState} from "react";
import {ChevronLeft,ChevronRight} from "lucide-react";
import {monthCalendar,money,percent,dateKey} from "./referenceModel";

export function Surface({title,subtitle,badge,children,className=""}) {return <section className={`tj-card tj-panel ref-surface ${className}`}><header className="ref-section-head"><div>{title&&<h3>{title}</h3>}{subtitle&&<p>{subtitle}</p>}</div>{badge&&<span className="ref-badge">{badge}</span>}</header>{children}</section>;}
export function Tile({label,value,note,tone="",children}) {return <div className={`ref-tile ${tone?`ref-tone-${tone}`:""}`}><small>{label}</small><strong>{value}</strong>{note&&<p>{note}</p>}{children}</div>;}
export function Meter({value=0,tone="green"}) {return <div className="ref-meter"><i className={`ref-meter-${tone}`} style={{width:`${Math.max(0,Math.min(100,value))}%`}}/></div>;}
export function Tabs({items,value,onChange,label="View"}) {return <div className="ref-tabs" role="tablist" aria-label={label}>{items.map(item=><button type="button" role="tab" aria-selected={value===item} className={value===item?"is-active":""} key={item} onClick={()=>onChange(item)}>{item}</button>)}</div>;}

export function AccountGuardrails({account,guardrails:g}) {
  if(!g?.enabled)return null;
  const now=new Date(), month=dateKey(now).slice(0,7),year=String(now.getFullYear()),trades=account.trades||[];
  const items=[
    {label:"Monthly Goal",date:now.toLocaleDateString(undefined,{month:"long",year:"numeric"})+" goal",value:g.monthlyPnl,target:g.monthlyGoal,count:trades.filter(t=>t.date?.startsWith(month)).length,period:"month",foot:"Month pace"},
    {label:"Annual Goal",date:`${year} goal`,value:g.yearlyPnl,target:g.yearlyGoal,count:trades.filter(t=>t.date?.startsWith(year)).length,period:"year",foot:"Year pace",tone:"blue"},
    {label:"Daily Loss Cap",value:Math.max(0,-g.dailyPnl),target:g.dailyLossCap,count:trades.filter(t=>t.date===dateKey(now)).length,period:"day",foot:"Daily buffer",loss:true},
    {label:"Monthly Loss Cap",value:Math.max(0,-g.monthlyPnl),target:g.monthlyLossCap,count:trades.filter(t=>t.date?.startsWith(month)).length,period:"month",foot:"Monthly buffer",loss:true},
  ];
  return <Surface className="ref-guardrails ref-grid-surface" badge={g.tradeEntryLocked?"Paused":"Live"}><div className="ref-guardrail-intro"><small className="ref-eyebrow">Account Guardrails</small><h3>Targets and limits are active</h3><p>Tilted progress tiles keep your goal pace, drawdown buffer, and live percentages readable at a glance.</p></div><div className="ref-guardrail-grid">{items.map(item=>{const pct=item.target>0?Math.max(0,item.value)/item.target*100:0,hit=item.target>0&&item.value>=item.target;return <article key={item.label} aria-label={item.label} className={`ref-guardrail ref-guardrail-${item.tone||"green"} ${hit&&item.loss?"ref-guardrail-breach":""}`}><div className="ref-guardrail-glow"/><div className="ref-guardrail-top"><div><small>{item.date||item.label}</small><strong>{money(item.value)} / {item.target?money(item.loss?-item.target:item.target,true):"Off"}</strong><span className="ref-badge">{!item.target?"Optional":hit?(item.loss?"Paused":"Cleared"):(item.loss?"Open":"Building")}</span></div><aside><b>{pct.toFixed(1)}%</b><small>{item.loss?`used this ${item.period}`:"of target"}</small><Meter value={pct} tone={item.tone||"green"}/></aside></div><p>{!item.target?"Set a value in Account Settings":item.loss?`${money(Math.max(0,item.target-item.value),true)} buffer left`:`${money(Math.abs(item.target-item.value),true)} ${hit?"above target":`left this ${item.period}`}`}</p><footer><span>{item.count} trades {item.period==="day"?"today":`this ${item.period}`}</span><b>{item.foot}</b></footer></article>;})}</div><p className="ref-guardrail-note">When a loss limit is hit, trade logging pauses until the next reset period while markups stay open for preparation and review.</p></Surface>;
}

export function SharedCalendar({account,monthCursor,setMonthCursor,onDayClick,filters=false}) {
  const [enabled,setEnabled]=useState(["win","loss","none","be"]);
  const {weeks,stats,activeDays}=monthCalendar(account.trades,account.balance,account.breakevenCap,monthCursor);
  const year=monthCursor.getFullYear(),month=monthCursor.getMonth();
  return <section className="tj-card tj-panel ref-calendar"><header className="ref-calendar-head"><div className="tj-month-nav"><button className="tj-icon-btn" aria-label="Previous month" onClick={()=>setMonthCursor(new Date(year,month-1,1))}><ChevronLeft size={15}/></button><strong>{monthCursor.toLocaleDateString(undefined,{month:"long",year:"numeric"})}</strong><button className="tj-icon-btn" aria-label="Next month" onClick={()=>setMonthCursor(new Date(year,month+1,1))}><ChevronRight size={15}/></button><button className="tj-btn-outline tj-btn-small" onClick={()=>setMonthCursor(new Date())}>This month</button></div><div className="ref-calendar-totals"><b className={stats.pnl<0?"tj-red":"tj-green"}>{money(stats.pnl,true)}</b><small>{activeDays} days</small><span className="tj-pill tj-pill-green">{stats.wins}W</span><span className="tj-pill tj-pill-red">{stats.losses}L</span><span className="tj-pill tj-pill-blue">{stats.count-stats.wins-stats.losses} B/E</span></div></header>
    {filters&&<><div className="tj-month-summary">{[["Profit",stats.wins,"tj-green"],["Loss",stats.losses,"tj-red"],["B-E",stats.count-stats.wins-stats.losses,"tj-blue"],["Trades",stats.count,""]].map(([name,count,cls])=><div key={name}><strong className={cls}>{count}</strong><small>{name}</small></div>)}</div><div className="ref-calendar-filters">{[["win","Winning Days"],["loss","Losing Days"],["none","No Trade Days"],["be","B-E Days"]].map(([key,label])=><button className={`ref-filter ${enabled.includes(key)?"is-active":""}`} key={key} aria-pressed={enabled.includes(key)} onClick={()=>setEnabled(s=>s.includes(key)?s.filter(x=>x!==key):[...s,key])}><i className={`ref-dot-${key}`}/>{label}</button>)}</div></>}
    <div className="ref-calendar-body"><div className="ref-calendar-inset"><div className="ref-weekdays">{["Mon","Tue","Wed","Thu","Fri","Sat","Sun"].map(d=><span key={d}>{d}</span>)}</div><div className="ref-calendar-grid">{weeks.flatMap(w=>w.days).map((cell,i)=>cell?<button type="button" key={cell.date} disabled={!cell.count} aria-label={`${cell.date}, ${cell.count} trades, ${money(cell.pnl)}`} className={`ref-day ref-day-${cell.kind} ${cell.date===dateKey(new Date())?"ref-day-today":""} ${!enabled.includes(cell.kind)?"ref-day-filtered":""}`} onClick={()=>onDayClick(cell.date)}><span className="ref-day-number">{cell.day}{cell.date===dateKey(new Date())&&<em>Today</em>}</span><span className="ref-day-result">{cell.count>0&&<><b>{money(cell.pnl,true)}</b><small>{cell.count}</small></>}</span></button>:<div className="ref-day-empty" key={`blank-${i}`}/>)}</div></div><aside className="ref-week-rail">{weeks.map((week,i)=><div className={`ref-week ${week.count?"ref-week-active":""}`} key={i}><div><small>Week {i+1}</small><b className={week.pnl<0?"tj-red":week.pnl>0?"tj-green":""}>{percent(week.returnPct)}</b></div><Meter value={week.wr} tone={week.pnl<0?"red":"green"}/><p>{week.count?`${week.count} days · ${week.wr.toFixed(0)}% win`:"Quiet week"}</p></div>)}</aside></div>
  </section>;
}
